server {
    listen 80;
    listen [::]:80;
    server_name d.magicboxie.com;

    include snippets/acme-challenge.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name d.magicboxie.com;

    ssl_certificate /etc/letsencrypt/live/d.magicboxie.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/d.magicboxie.com/privkey.pem;
    include snippets/ssl-params.conf;

    location / {
        return 302 https://raw.githubusercontent.com/kriogenx0/magicboxie-device/main/install.sh;
    }
}
